### ISSUE TITLE
Xcode project for 'Multiplatform' does not work with Xcode 12 public release

### ISSUE THREAD

**Issue by funky-monkey** [rickwierenga/heartbeat-tutorials#1]
Hello @rickwierenga , 

Just read your [fantastic article](https://heartbeat.fritz.ai/building-a-multi-platform-app-with-swiftui-5336bce94689) and downloaded the code. I'm using Xcode Version 12.0 (12A7209) appstore version. 

I'm getting a lot of errors regarding the @main and that the compiler has a lot of **'Cannot find type 'some .swift file' in scope'** errors. This happens when running the macOS scheme. Running the iOS scheme works fine.

Could be something with the beta version to release version of Xcode?

Slightly unrelated; Your article states an option for creating a 'Multiplatform app' (one of the first screenshots), but this Xcode version only has an option for 'Multiplatform game'...

**Comment by rickwierenga** [comment]
Sorry for my late response. I think I missed the notification. Anyways, thanks for letting me know! I'll update the tutorial next week after I've finished my midterms.

**Comment by funky-monkey** [comment]
No worries, I saw this changed in the latest Xcode.

Good luck on your midterms 👍
