### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by flooie** [rickwierenga/heartbeat-tutorials#4]
Is it possible to build all of this inside a docker container?

**Comment by dhairya137** [comment]
Not everything in one container. But you can upload every thing one by one as image on one repository

**Comment by flooie** [comment]
Sorry that was a bit of a terrible question.

I've been trying to build the CoreML API Dockerfile locally.  I want to test using an image classifier inside a docker container from your tutorial.  When I build the Dockerfile it always crashes at the same spot ---

`Step 7/15 : RUN swift build -c release && mv `swift build -c release --show-bin-path` /build/bin
`

`/app/Sources/App/Controllers/Classifier.swift:8:8: error: no such module 'CoreImage'
import CoreImage
       ^
The command '/bin/sh -c swift build -c release && mv `swift build -c release --show-bin-path` /build/bin' returned a non-zero code: 1
`

I'm clearly missing something about integrating apples framework into the docker container.  Any idea what I'm doing wrong?

**Comment by rickwierenga** [comment]
Hi, the Dockerfile was taken from [here](https://github.com/vapor/web-template/blob/master/web.Dockerfile). CoreImage is a proprietary framework from Apple so I guess it will only work on Apple devices. AWS offers Mac instances (see [this](https://aws.amazon.com/ec2/instance-types/mac/)) but I have never used those personally.

**Comment by flooie** [comment]
@rickwierenga thanks that clears things up for me.
